import { desc, eq } from 'drizzle-orm';
import { db } from './db';
import { turns } from './schema';
import type { AskOutcome, RetrievedSnapshot } from './ask';
import type { GroundingVerdict } from './ground';

/** Turn logging repository: one row per turn, not per message. The only module that writes
 *  `turns` and, for history assembly, reads recent rows back. See docs/ask-agent/03-data-model.md. */

export interface TurnLogEntry {
  id: string;
  conversationId: string;
  sessionId: string;
  question: string;
  answer: string | null;
  outcome: AskOutcome;
  grounding: GroundingVerdict;
  topScore: number;
  /** See `RetrievedSnapshot` (lib/ask/ask.ts): a copy of what was read, not a pointer. */
  retrieved: RetrievedSnapshot[];
  askVersion: string;
  corpusHash: string;
  latencyMs: number;
  inputTokens: number;
  outputTokens: number;
  embedTokens: number;
  costUsd: number;
}

/** Inserts one `turns` row. `id` is generated by the caller, not left to the column default, so
 *  the disconnect path in lib/ask/stream.ts can reason about the turn before the insert runs. */
export async function insertTurn(entry: TurnLogEntry): Promise<void> {
  await db()
    .insert(turns)
    .values({
      id: entry.id,
      conversationId: entry.conversationId,
      sessionId: entry.sessionId,
      question: entry.question,
      answer: entry.answer,
      outcome: entry.outcome,
      grounding: entry.grounding,
      topScore: entry.topScore,
      retrieved: entry.retrieved,
      askVersion: entry.askVersion,
      corpusHash: entry.corpusHash,
      latencyMs: entry.latencyMs,
      inputTokens: entry.inputTokens,
      outputTokens: entry.outputTokens,
      embedTokens: entry.embedTokens,
      // turns.cost_usd is a Drizzle numeric column in default string mode, matching what a
      // read returns; see schema.ts's comment on this column.
      costUsd: entry.costUsd.toString(),
    });
}

export interface StoredTurn {
  question: string;
  answer: string | null;
  outcome: string;
}

/** Upper bound on rows a single history fetch pulls back, applied before lib/ask/history.ts's
 *  token-budget trimming runs in memory. Generous headroom above realistic daily traffic. */
const MAX_HISTORY_TURNS_FETCHED = 200;

/** Most recent turns for `conversationId`, oldest first. A null `question` (nulled by the
 *  90-day retention job) is filtered out rather than replayed as empty text. */
export async function fetchRecentTurns(conversationId: string): Promise<StoredTurn[]> {
  const rows = await db()
    .select({ question: turns.question, answer: turns.answer, outcome: turns.outcome })
    .from(turns)
    .where(eq(turns.conversationId, conversationId))
    .orderBy(desc(turns.createdAt))
    .limit(MAX_HISTORY_TURNS_FETCHED);

  return rows
    .reverse()
    .filter((row): row is typeof row & { question: string } => row.question !== null)
    .map((row) => ({ question: row.question, answer: row.answer, outcome: row.outcome }));
}
